---
- name: 'Install python3'
  hosts: VM2
  become: true
  gather_facts: false

- name: 'Playbook to configure IPA client'
  hosts: VM2
  become: true
  collections:
    - 'freeipa.ansible_freeipa'
  vars:
    ipaserver_ip_addresses: '192.168.56.10'
    ipaserver_hostname: 'vm1.test.local'
    ipaadmin_principal: 'admin'
    ipaserver_domain: 'test.local'
    ipaserver_realm: 'TEST.LOCAL'
    ipaadmin_password: 'freeipass'  # Поменяйте на строку в одинарных кавычках
    ipaclient_configure_dns_resolver: yes
    ipaclient_dns_servers: '192.168.56.10'

  roles:
    - role: 'ipaclient'
      state: 'present'

  tasks:
    - name: 'Install Epel'
      yum:
       name: epel-release
       state: present

    - name: Install SCL (Software Collections) for Ruby 2.7
      yum:
        name: centos-release-scl
        state: present


    - name: 'Install Puppet repository'
      yum:
        name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
        state: present

    - name: 'Установка репозитория Foreman (замените на ваш репозиторий, если нужно)'
      yum:
        name: https://yum.theforeman.org/releases/1.24/el7/x86_64/foreman-release-1.24.0-4.el7.noarch.rpm
        state: present

    - name: Remove the line from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127.0.1.1 vm2\.test\.local vm2$'

    - name: 'Установка Foreman'
      yum:
        name: foreman-installer
        state: present

    - name: Запустить foreman-installer
      command: foreman-installer
      args:
        warn: false  # Если нужно игнорировать предупреждения
      register: foreman_installer_result

    - name: Вывести результат
      debug:
        var: foreman_installer_result.stdout_lines # Выводит пароль на подлючение

- name: Настройка правила iptables для NAT
  hosts: VM2
  become: yes
  tasks:
    - name: Добавить правило PREROUTING для NAT
      shell: iptables -t nat -A PREROUTING -p tcp --dport 8081 -i eth1 -j DNAT --to-destination 192.168.56.20:80




