---

- hosts: VM3
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Устанока зависимостей
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-docker
          - gnupg2
          - pass
      tags:
        - docker

    - name: Добавление Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      tags:
        - docker

    - name: Добавление Docker репозитария
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      tags:
        - docker

    - name: Update apt cache (again)
      ansible.builtin.apt:
        update_cache: yes

    - name: Установка Docker
      ansible.builtin.package:
        name: docker-ce
        state: present
      tags:
        - docker

    - name: Старт Docker сервиса
      ansible.builtin.service:
        name: docker
        state: started
      tags:
        - docker


    - name: Копия Dockerfile на VM3
      ansible.builtin.copy:
        src: /home/ruslan/home_work/Dockerfile
        dest: /home

      tags:
        - docker

    - name: Построение Docker-образа
      docker_image:
        build:
          path: /home
          dockerfile: Dockerfile
        name: zbx_vagrant
        source: build


- name: Запуск докера
  hosts: VM3
  become: yes
  tasks:
    - name: Запуск
      shell: docker run --name zabbix-v -p 80:80 -p 10051:10051 -p 3306:3306 zbx_vagrant
